### PR TITLE
Use latest Ruby Version in .travis.yml

### PR DESCRIPTION
**Pull request by yhirano55**
And update dependeicies. Fixed CI problems.

Refs: https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-377680126

### CODE REVIEW

**Comment by eregon** [comment]
Thank you!
It's unfortunate this Travis or `rvm` bug is still present, but thanks for the fix.

**Comment by andrykonchin** [comment]
@eregon Are you going to get rid of Ruby 2.2 support? What's the policy for Ruby versions support?

**Comment by eregon** [comment]
I think we should follow ruby/spec and therefore drop versions when MRI stops maintenance.

Since
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/
> Ruby 2.2 is under the state of the security maintenance phase, until the end of the March of 2018. After the date, maintenance of Ruby 2.2 will be ended.

and we are in April, indeed 2.2 is no longer maintained, good catch.

So we should indeed remove 2.2, both for mspec and ruby/spec.
@andrykonchin Would you like to do it?
For ruby/spec, there is `tool/remove_old_guards.rb` in mspec to remove old guards like `ruby_version_is "2.2" do` easily.

**Comment by andrykonchin** [comment]
@eregon 
> Would you like to do it?

Yep. I will work on it soon

**Pull request merged**
